name = "day1"
description = "AoC 2022 Day 1 solution"
version = "0.1.0-dev"

authors = ["zetah11"]
maintainers = ["zetah11 <findusxi@protonmail.com>"]
maintainers-logins = ["zetah11"]

executables = ["day1"]
[[depends-on]]
gnatprove = "^12.1.1"
